<?php

  function traffy_menu() {

    $items['traffy/test/%'] = array(
        'title' => 'Traffy API CCTV testing',
        'description' => 'Testing traffy CCTV api on drupal7',
        'page callback' => 'test_api',
        'page arguments' => array(2),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    
    $items['traffy/wrapper/%'] = $items['traffy/test/%']; 
      
    $items['admin/traffy/settings'] = array(
        'title' => 'Traffy API configuration',
        'description' => 'Testing traffy api with drupal7',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('traffy_admin_settings'),
        'access arguments' => array('administer site configuration'),
        'file' => 'traffy.admin.inc',
        'menu_name' => 'traffy',
    );
   
    $items['traffy/hello'] = array(
        'title' => 'Hello Traffy API testing on Drupal7.0',
        'description' => 'Testing traffy api on Drupal7.0',
        'page callback' => 'hello_traffy',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    return $items;
  }

  function hello_traffy() {
    return "Hello drupal by api traffy!";
  }

  function test_api($api_to_call) {
    $traffy  = get_api_info(); 
    $link_opts = array('api'=> $api_to_call,
                       'appid' => $traffy['appid'],
                       'key' => $traffy['apikey'],
                      );
    if (!isset($_GET['format'])) {
      $_GET['format'] = "JSON";
    }

    foreach ($_GET as $key => $value) {
      if ($key != 'q') {
        $link_opts[$key] = $value;
      }
    }

    $url = url($traffy['service'], array('query' => $link_opts));
    drupal_set_message($url);
    $options = array(
      'headers' => get_http_headers(), 
      'method' => 'POST', 
      'data' => NULL, 
      'max_redirects' => 3, 
      'timeout' => 10.0, 
      'context' => NULL, 
    ); 

      $ret = '';
      $res = drupal_http_request($url, $options); 
      if ($res->code != 200 ) {
        drupal_set_message(print_r($res, 1), 'error');
        drupal_set_message($res->error, 'error');
        $ret = 'error '. $res->code .': ' . $res->error;
      }
      else {
        switch ($api_to_call) {
          case "getCCTV":
            $raw_json = $res->data;
            /**
              *  I CAN'T PARSE JSON !!!!
              *  Return javascript code,,, : ((( 
              *
              */
            $ret = "<script> 
              jQuery(document).ready(function() { 
                jQuery('#content').append('<div id=\'traffy\'> <div class=\'loading\'>Loading</div> </div>');
                var c = ". $raw_json ."
                jQuery.each(c[0], function(k, v) {
                  var img_ele = jQuery('<img />'); img_ele.attr('src', v.url);
                  jQuery('#traffy').append(img_ele);
                  if(typeof(console) !== 'undefined' && console != null) {
                    console.log(k, v);
                  }
                });
                jQuery('.loading').remove();
              });
            </script>";
            break;
          case "getcctvimg":
              drupal_add_http_header('Content-Type', 'image/jpeg');
              print $res->data;
              exit;
            break;
          default;
              $ret = 'api not found';
        }
      } 
    return $ret; 
  }
  function get_api_info() {
    $api_service = variable_get('traffy_service_url', 'http://athena.traffy.in.th/apis/apitraffy.php');
    $apikey = variable_get('traffy_apikey', '');
    $appid= variable_get('traffy_appid', '');
    $traffy = array('service' => $api_service, 
                 'apikey' => $apikey,
                 'appid' => $appid,
                );
    return $traffy; 
  }  
  function get_http_headers () {
    $host = $_SERVER['SERVER_NAME'];
    $headers = array(
        'Content-Type' => 'application/x-www-form-urlencoded; charset=utf-8',
        'Host' => $host, 
        'Referer' => 'http://'.$host,
    ); 
    return $headers;
  }

